package com.loanms.service;
import com.loanms.db.Database; import com.loanms.model.Customer; import java.sql.*; import java.util.*;
public class CustomerService {
 public Customer add(String name,String phone,String email){validate(name,phone); try(Connection c=Database.connect();PreparedStatement p=c.prepareStatement("INSERT INTO customer(name,phone,email) VALUES(?,?,?)",Statement.RETURN_GENERATED_KEYS)){p.setString(1,name.trim());p.setString(2,phone.trim());p.setString(3,email);p.executeUpdate();try(ResultSet r=p.getGeneratedKeys()){return new Customer(r.next()?r.getInt(1):0,name.trim(),phone.trim(),email);}}catch(SQLException e){throw new IllegalStateException("Could not add customer: "+e.getMessage(),e);}}
 public void update(int id,String name,String phone,String email){validate(name,phone); try(Connection c=Database.connect();PreparedStatement p=c.prepareStatement("UPDATE customer SET name=?,phone=?,email=? WHERE id=?")){p.setString(1,name.trim());p.setString(2,phone.trim());p.setString(3,email);p.setInt(4,id);if(p.executeUpdate()==0)throw new IllegalArgumentException("Customer not found");}catch(SQLException e){throw new IllegalStateException(e);}}
 public void delete(int id){try(Connection c=Database.connect();PreparedStatement p=c.prepareStatement("DELETE FROM customer WHERE id=?")){p.setInt(1,id);if(p.executeUpdate()==0)throw new IllegalArgumentException("Customer not found");}catch(SQLException e){throw new IllegalStateException("Cannot delete customer with linked loans",e);}}
 public List<Customer> list(){List<Customer> out=new ArrayList<>();try(Connection c=Database.connect();ResultSet r=c.createStatement().executeQuery("SELECT * FROM customer ORDER BY id DESC")){while(r.next())out.add(new Customer(r.getInt("id"),r.getString("name"),r.getString("phone"),r.getString("email")));return out;}catch(SQLException e){throw new IllegalStateException(e);}}
 private void validate(String n,String p){if(n==null||n.isBlank()||p==null||p.isBlank())throw new IllegalArgumentException("Name and phone are required");}
}
